### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by BITLiuYu** [randoms/ROSTest#1]
我的系统是Ubuntu，所有的设置也是按照您的教程做的，但是run的时候就立即闪退。
其中，修改app的build.gradle时出现错误：
Error:Conflict with dependency 'com.google.code.findbugs:jsr305' in project ':app'. Resolved versions for app (1.3.9) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
按照网上的方式，进行修改，在Android节点下添加:
configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }
不知道是否会影响

我的build.gradle为：
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    //buildToolsVersion '25.0.0'
    defaultConfig {
        applicationId "com.example.rostest"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }

    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'

    //androidTestCompile 'com.android.support.test:runner:1.0.2'
    //androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'

    compile 'org.ros.android_core:android_10:[0.3,0.4)'
}

**Comment by randoms** [comment]
编译器设置问题，详情参考 [这里](https://community.bwbot.org/topic/627/%E5%9C%A8android%E4%B8%AD%E4%BD%BF%E7%94%A8ros/8)
